[project]
name = 'stacker-score-tracker'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.stacker-score-tracker]
path = 'contracts/stacker-score-tracker.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
